import '../styles/globals.css';
import Header from '../components/Header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ALEKUSTN | Home',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ fontSize: '16px' }}>
      <body style={{ fontFamily: 'Georgia, serif', fontSize: '16px' }}>
        <Header />
        {children}
      </body>
    </html>
  );
}