import type { Metadata } from 'next'
import './globals.css'
import HeaderTest from '@/components/HeaderTest'

export const metadata: Metadata = {
  title: 'ALEKUSTN | Home',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderTest />
        {children}
      </body>
    </html>
  )
}